import { Geist, Geist_Mono, Rambla } from "next/font/google";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rambla = Rambla({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-rambla",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${rambla.variable}`}>
        <Navbar/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
